name: Deploy Donaciones Site

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build deploy directory
        run: |
          rm -rf .deploy || true
          mkdir .deploy
          cp -R ./* .deploy || true
          # remove the workflow folder from deploy
          rm -rf .deploy/.github || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.deploy
          cname: donaciones.yag3r.cm
